/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_gbc_jni_IcpHandler */

#ifndef _Included_edu_gbc_jni_IcpHandler
#define _Included_edu_gbc_jni_IcpHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_gbc_jni_IcpHandler
 * Method:    nativeIterativeClosestPoint
 * Signature: (II[FII[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_edu_gbc_jni_IcpHandler_nativeIterativeClosestPoint
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
